// this is a list of country names associated with their ITU codes
var ship_itu = {"AFG": "Afghanistan",
"AFS": "South Africa (Republic of)",
"AGL": "Angola (Republic of)",
"ALB": "Albania (Republic of)",
"ALG": "Algeria (People 's Democratic Republic of)",
"AND": "Andorra (Principality of)",
"ARG": "Argentine Republic",
"ARM": "Armenia (Republic of)",
"ARS": "Saudi Arabia (Kingdom of)",
"ATG": "Antigua and Barbuda",
"AUS": "Australia",
"AUT": "Austria",
"AZE": "Azerbaijani Republic",
"B": "Brazil (Federative Republic of)",
"BAH": "Bahamas (Commonwealth of the)",
"BDI": "Burundi (Republic of)",
"BEL": "Belgium",
"BEN": "Benin (Republic of)",
"BFA": "Burkina Faso",
"BGD": "Bangladesh (People 's Republic of)",
"BHR": "Bahrain (Kingdom of)",
"BIH": "Bosnia and Herzegovina",
"BLR": "Belarus (Republic of)",
"BLZ": "Belize",
"BOL": "Bolivia (Republic of)",
"BOT": "Botswana (Republic of)",
"BRB": "Barbados",
"BRM": "Myanmar (Union of)",
"BRU": "Brunei Darussalam",
"BTN": "Bhutan (Kingdom of)",
"BUL": "Bulgaria (Republic of)",
"CAF": "Central African Republic",
"CAN": "Canada",
"CBG": "Cambodia (Kingdom of)",
"CHL": "Chile",
"CHN": "China (People 's Republic of)",
"CLM": "Colombia (Republic of)",
"CLN": "Sri Lanka (Democratic Socialist Republic of)",
"CME": "Cameroon (Republic of)",
"COD": "Democratic Republic of the Congo",
"COG": "Congo (Republic of the)",
"COM": "Comoros (Union of the)",
"CPV": "Cape Verde (Republic of)",
"CTI": "Côte d'Ivoire (Republic of)",
"CTR": "Costa Rica",
"CUB": "Cuba",
"CVA": "Vatican City State",
"CYP": "Cyprus (Republic of)",
"CZE": "Czech Republic",
"D": "Germany (Federal Republic of)",
"DJI": "Djibouti (Republic of)",
"DMA": "Dominica (Commonwealth of)",
"DNK": "Denmark",
"DOM": "Dominican Republic",
"E": "Spain",
"EGY": "Egypt (Arab Republic of)",
"EQA": "Ecuador",
"ERI": "Eritrea",
"EST": "Estonia (Republic of)",
"ETH": "Ethiopia (Federal Democratic Republic of)",
"F": "France",
"FIN": "Finland",
"FJI": "Fiji (Republic of)",
"FSM": "Micronesia (Federated States of)",
"G": "United Kingdom of Great Britain and Northern Ireland",
"GAB": "Gabonese Republic",
"GEO": "Georgia",
"GHA": "Ghana",
"GMB": "Gambia (Republic of the)",
"GNB": "Guinea-Bissau (Republic of)",
"GNE": "Equatorial Guinea (Republic of)",
"GRC": "Greece",
"GRD": "Grenada",
"GTM": "Guatemala (Republic of)",
"GUI": "Guinea (Republic of)",
"GUY": "Guyana",
"HND": "Honduras (Republic of)",
"HNG": "Hungary (Republic of)",
"HOL": "Netherlands (Kingdom of the)",
"HRV": "Croatia (Republic of)",
"HTI": "Haiti (Republic of)",
"I": "Italy",
"IND": "India (Republic of)",
"INS": "Indonesia (Republic of)",
"IRL": "Ireland",
"IRN": "Iran (Islamic Republic of)",
"IRQ": "Iraq (Republic of)",
"ISL": "Iceland",
"ISR": "Israel (State of)",
"J": "Japan",
"JMC": "Jamaica",
"JOR": "Jordan (Hashemite Kingdom of)",
"KAZ": "Kazakhstan (Republic of)",
"KEN": "Kenya (Republic of)",
"KGZ": "Kyrgyz Republic",
"KIR": "Kiribati (Republic of)",
"KNA": "Saint Kitts and Nevis (Federation of)",
"KOR": "Korea (Republic of)",
"KRE": "Democratic People 's Republic of Korea",
"KWT": "Kuwait (State of)",
"LAO": "Lao People 's Democratic Republic",
"LBN": "Lebanon",
"LBR": "Liberia (Republic of)",
"LBY": "Socialist People 's Libyan Arab Jamahiriya",
"LCA": "Saint Lucia",
"LIE": "Liechtenstein (Principality of)",
"LSO": "Lesotho (Kingdom of)",
"LTU": "Lithuania (Republic of)",
"LUX": "Luxembourg",
"LVA": "Latvia (Republic of)",
"MAU": "Mauritius (Republic of)",
"MCO": "Monaco (Principality of)",
"MDA": "Moldova (Republic of)",
"MDG": "Madagascar (Republic of)",
"MEX": "Mexico",
"MHL": "Marshall Islands (Republic of the)",
"MKD": "Republic of Macedonia",
"MLA": "Malaysia",
"MLD": "Maldives (Republic of)",
"MLI": "Mali (Republic of)",
"MLT": "Malta",
"MNE": "Montenegro (Republic of)",
"MNG": "Mongolia",
"MOZ": "Mozambique (Republic of)",
"MRC": "Morocco (Kingdom of)",
"MTN": "Mauritania (Islamic Republic of)",
"MWI": "Malawi",
"NCG": "Nicaragua",
"NGR": "Niger (Republic of the)",
"NIG": "Nigeria (Federal Republic of)",
"NMB": "Namibia (Republic of)",
"NOR": "Norway",
"NPL": "Nepal",
"NRU": "Nauru (Republic of)",
"NZL": "New Zealand",
"OMA": "Oman (Sultanate of)",
"PAK": "Pakistan (Islamic Republic of)",
"PHL": "Philippines (Republic of the)",
"PNG": "Papua New Guinea",
"PNR": "Panama (Republic of)",
"POL": "Poland (Republic of)",
"POR": "Portugal",
"PRG": "Paraguay (Republic of)",
"PRU": "Peru",
"QAT": "Qatar (State of)",
"ROU": "Romania",
"RRW": "Rwandese Republic",
"RUS": "Russian Federation",
"S": "Sweden",
"SDN": "Sudan (Republic of the)",
"SEN": "Senegal (Republic of)",
"SEY": "Seychelles (Republic of)",
"SLM": "Solomon Islands",
"SLV": "El Salvador (Republic of)",
"SMO": "Samoa (Independent State of)",
"SMR": "San Marino (Republic of)",
"SNG": "Singapore (Republic of)",
"SOM": "Somali Democratic Republic",
"SRB": "Serbia (Republic of)",
"SRL": "Sierra Leone",
"SSD": "South Sudan (Republic of)",
"STP": "São Tomé and Príncipe (Democratic Republic of)",
"SUI": "Switzerland (Confederation of)",
"SUR": "Suriname (Republic of)",
"SVK": "Slovakia",
"SVN": "Slovenia (Republic of)",
"SWZ": "Swaziland (Kingdom of)",
"SYR": "Syrian Arab Republic",
"TCD": "Chad (Republic of)",
"TGO": "Togolese Republic",
"THA": "Thailand",
"TJK": "Tajikistan (Republic of)",
"TKM": "Turkmenistan",
"TLS": "Timor-Leste (Democratic Republic of)",
"TON": "Tonga (Kingdom of)",
"TRD": "Trinidad and Tobago",
"TUN": "Tunisia",
"TUR": "Turkey",
"TUV": "Tuvalu",
"TZA": "Tanzania (United Republic of)",
"UAE": "United Arab Emirates",
"UGA": "Uganda (Republic of)",
"UKR": "Ukraine",
"URG": "Uruguay (Eastern Republic of)",
"USA": "United States of America",
"UZB": "Uzbekistan (Republic of)",
"VCT": "Saint Vincent and the Grenadines",
"VEN": "Venezuela (Bolivarian Republic of)",
"VTN": "Vietnam (Socialist Republic of)",
"VUT": "Vanuatu (Republic of)",
"YEM": "Yemen (Republic of)",
"ZMB": "Zambia (Republic of)",
"ZWE": "Zimbabwe (Republic of)",
"AIA": "Anguilla",
"ALS": "Alaska (State of)",
"AMS": "Saint Paul and Amsterdam Islands",
"AOE": "Western Sahara",
"ASC": "Ascension Island",
"ATA": "Antarctic",
"AZR": "Azores",
"BER": "Bermuda",
"BIO": "Chagos Islands (Indian Ocean)",
"BVT": "Bouvet Island",
"CG7": "CUB(Guantanamo) (7).[6]",
"CHR": "Christmas Island (Indian Ocean)",
"CKH": "Cook Islands",
"CNR": "Canary Islands",
"CPT": "Clipperton Island",
"CRO": "Crozet Archipelago",
"CYM": "Cayman Islands",
"DGA": "Diego Garcia",
"FLK": "Falkland Islands (Malvinas)",
"FRO": "Faroe Islands",
"GCA": "United Kingdom (Non-metropolitan)  xe2 x80 x93 Region 1",
"GCC": "United Kingdom  xe2 x80 x93 Region 3",
"GIB": "Gibraltar",
"GRL": "Greenland",
"GUF": "Guiana (French Department of)",
"GUM": "Guam",
"HKG": "Hong Kong (Special Administrative Region of China)",
"HMD": "Heard and McDonald Islands",
"HWA": "Hawaii (State of)",
"HWL": "Howland Island",
"ICO": "Cocos (Keeling) Islands",
"JAR": "Jarvis Island",
"JON": "Johnston Island",
"KER": "Kerguelen Islands",
"MAC": "Macau (Special Administrative Region of China)",
"MDR": "Madeira",
"MDW": "Midway Islands",
"MRA": "Northern Mariana Islands (Commonwealth of the)",
"MRN": "Marion Island",
"MRT": "Martinique (French Department of)",
"MSR": "Montserrat",
"MYT": "Mayotte (Territorial Collectivity of)",
"NCL": "New Caledonia",
"NFK": "Norfolk Island",
"NIU": "Niue",
"OCE": "French Polynesia",
"PAQ": "Easter Island",
"PHX": "Phoenix Islands",
"PLM": "Palmyra Island",
"PLW": "Palau (Republic of)[7]",
"PTC": "Pitcairn Island",
"PTR": "Puerto Rico",
"REU": "Réunion (French Department of)",
"ROD": "Rodrigues",
"SCG": "ex Serbia and Montenegro  xe2 x86 x92 SRB",
"SHN": "Saint Helena",
"SMA": "American Samoa",
"SPM": "Saint Pierre and Miquelon (Territorial Collectivity of)",
"SWN": "Swan Islands",
"TCA": "Turks and Caicos Islands",
"TKL": "Tokelau",
"TRC": "Tristan da Cunha",
"VIR": "United States Virgin Islands",
"VRG": "British Virgin Islands",
"WAK": "Wake Island",
"WAL": "Wallis and Futuna Islands",
"XAA": "shared throughout the world",
"XAX": " ",
"XBR": "special use",
"XBY": "Abyei area",
"XCQ": "ex Caroline Islands  xe2 x86 x92 FSM + PLW",
"XCS": "ex TCH Czechoslovakia  xe2 x86 x92 CZE + SVK",
"XGZ": "Gaza Strip",
"XMM": "inter-ship communications",
"XOA": "International Civil Aviation Organization",
"XR1": "Region 1 (RR 5.3)",
"XR2": "Region 2 (RR 5.4)",
"XR3": "Region 3 (RR 5.5)",
"XRY": "Antarctic Region (RR AP 26/5.2)",
"XSC": "ex SCG Serbia and Montenegro",
"XSD": "ex Republic of the Sudan before 14 July 2011  xe2 x86 x92 SDN + SSD",
"XSP": "Spratly Islands",
"XSU": "ex URS Soviet Union  xe2 x86 x92 RUS +  xe2 x80 xa6",
"XUN": "United Nations",
"XWB": "West Bank",
"XWM": "World Meteorological Organization",
"XYU": "ex YUG Yugoslavia  xe2 x86 x92 SCG xe2 x80 xa6 + HRV + BIH + SVN",
"XYZ": "pending further developments regarding the administration responsible",
"XZZ": "administrative status is subject to special arrangements"}